export const work2019 = [
  {
    title: "2019",
    link: "2019",
    id: "Pediatric Surgery",
    src: "/assets/Work/2019/Pediatric Surgery, 2019, Oil on canvas, 150x200cm, 59x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 200 cm",
    sizeInch: "59 x 78.7 inches",
    date: "2019",
  },
  {
    id: "Pediatric Surgery 2",
    src: "/assets/Work/2019/2019_Pediatric_Surgery_2, 2019 Oil on canvas 165x200cm 65x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "165 x 200 cm",
    sizeInch: "65 x 78.7 inches",
    date: "2019",
  },
  {
    id: "Boiling Crayfish",
    src: "/assets/Work/2019/Boiling Crayfish, 2019 Oil on canvas 200x250 cm 78.7x98.4 inches.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 250 cm",
    sizeInch: "78.7 x 98.4 inches",
    date: "2019",
  },
  {
    id: "Chess Players",
    src: "/assets/Work/2019/Chess Players, 2019, oil on canvas, 150x200cm, 59x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 200 cm",
    sizeInch: "59 x 78.7 inches",
    date: "2019",
  },
  {
    id: "Father as a Baby",
    src: "/assets/Work/2019/Father As A Baby, 2019, Oil on canvas,100x150cm, 39.4x59 inches.webp",
    method: "Oil on canvas",
    sizeCm: "100 x 150 cm",
    sizeInch: "39.4 x 59 inches",
    date: "2019",
  },
  {
    id: "Grandma with the Microscope",
    src: "/assets/Work/2019/Grandma With The Microscope, 2019, Oil on canvas, 95x50cm, 37.4x19.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "95 x 50 cm",
    sizeInch: "37.4 x 19.7 inches",
    date: "2019",
  },
  {
    id: "Jewish Family 1932",
    src: "/assets/Work/2019/Jewish Family 1932, 2019, Oil on canvas,270x140cm, 106.3x55.1 inches.webp",
    method: "Oil on canvas",
    sizeCm: "270 x 140 cm",
    sizeInch: "106.3 x 55.1 inches",
    date: "2019",
  },
  {
    id: "Party 1976",
    src: "/assets/Work/2019/Party 1976, 2019, Oil on canvas, 82x45cm, 32.3x17.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "82 x 45 cm",
    sizeInch: "32.3 x 17.7 inches",
    date: "2019",
  },
  {
    id: "Seeing their Grandma",
    src: "/assets/Work/2019/Seeing Their Grandma, 2019, Oil on canvas, 160x160cm, 63x63 inches.webp",
    method: "Oil on canvas",
    sizeCm: "160 x 160 cm",
    sizeInch: "63 x 63 inches",
    date: "2019",
  },
  {
    id: "Surgery on the unknown Patient",
    src: "/assets/Work/2019/Surgery_On_The_Unknown_Patient, 2019 Oil on canvas 190x160cm 74.8x63 inches.webp",
    method: "Oil on canvas",
    sizeCm: "190 x 160 cm",
    sizeInch: "74.8 x 63 inches",
    date: "2019",
  },
  {
    id: "Two Sisters",
    src: "/assets/Work/2019/Two Sisters, 2019, Oil on canvas, 160x90cm, 63x35.4 inches.webp",
    method: "Oil on canvas",
    sizeCm: "160 x 90 cm",
    sizeInch: "63 x 35.4 inches",
    date: "2019",
  },
  {
    id: "Vacation 1969",
    src: "/assets/Work/2019/Vacation 1969, 2029, Oil on canvas, 100x60cm,  39.4x23.6 inches.webp",
    method: "Oil on canvas",
    sizeCm: "100 x 60 cm",
    sizeInch: "39.4 x 23.6 inches",
    date: "2019",
  },
];

export const work2020 = [
  {
    title: "2020",
    link: "2020",
    id: "Actress Kommisarjevskaya playing Nora",
    src: "/assets/Work/2020/Actress Kommisarjevskaya playing Nora,  based on the 1903 photograph  of Elena Morozovskaya, 2020, Oil on canvas, 190x160cm, 74.8x63 inches.webp",
    method: "Oil on canvas",
    sizeCm: "190 x 160 cm",
    sizeInch: "74.8 x 63 inches",
    date: "2020",
  },
  {
    id: "Adams Family",
    src: "/assets/Work/2020/Adams Family, 2020 Oil on canvas 195x130cm. 76.8x51.2 inches.webp",
    method: "Oil on canvas",
    sizeCm: "195 x 130 cm",
    sizeInch: "76.8 x 51.2 inches",
    date: "2020",
  },
  {
    id: "Dr. Mendeleev and his Colleagues before the Expedition to Siberia",
    src: "/assets/Work/2020/D.Mendeleev and his colleagues before the expedition to Siberia, 2020, Oil on canvas, 180x210cm, 70.9x82.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 210 cm",
    sizeInch: "70.9 x 82.7 inches",
    date: "2020",
  },
  {
    id: "Komissarjevskayas Theatre Actors posing in Costumes",
    src: "/assets/Work/2020/Komissarjevskayas Theatre Actors posing in costumes, 2020, Oil on canvas, 150x200cm, 59x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 200 cm",
    sizeInch: "59 x 78.7 inches",
    date: "2020",
  },
  {
    id: "Marias Sisters",
    src: "/assets/Work/2020/Marias Sisters, 2020, Oil on canvas, 195x130cm, 76.8x51.2 inches.webp",
    method: "Oil on canvas",
    sizeCm: "195 x 130cm",
    sizeInch: "76.8 x 51.2 inches",
    date: "2020",
  },
  {
    id: "Mum and Nietzsche",
    src: "/assets/Work/2020/Mum and Nietzsche, 2020, Oil on canvas, 46x33cm, 18.1x13 inches.webp",
    method: "Oil on canvas",
    sizeCm: "46 x 33 cm",
    sizeInch: "18.1 x 13 inches",
    date: "2020",
  },
  {
    id: "Posing for a Photograph",
    src: "/assets/Work/2020/Posing for a photograph, 2020, Oil on canvas, 240x200cm, 94.5x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "240 x 200 cm",
    sizeInch: "94.5 x 78.7 inches",
    date: "2020",
  },
  {
    id: "Zinoviis Kids",
    src: "/assets/Work/2020/Zinoviis kids, 2020, Oil on canvas, 130x195cm, 51.2x76.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "130 x 195 cm",
    sizeInch: "51.2 x 76.7 inches",
    date: "2020",
  },
];

export const work2021 = [
  {
    title: "2021",
    link: "2021",
    id: "Feast Scene",
    src: "/assets/Work/2021/Feast Scene, 2021 Oil on canvas 230x180cm 90.6x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "230 x 180 cm",
    sizeInch: "90.6 x 70.9 inches",
    date: "2021",
  },
  {
    id: "French Coastline",
    src: "/assets/Work/2021/French coastline, 2021 Oil on canvas 50x40cm 19.7x15.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "50 x 40 cm",
    sizeInch: "19.7 x 15.7 inches",
    date: "2021",
  },
  {
    id: "Mum on the Beach 1970",
    src: "/assets/Work/2021/Mum on the beach 1970, 2021 Oil on canvas 120x180cm 47.4x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "120 x 180 cm",
    sizeInch: "47.4 x 70.9 inches",
    date: "2021",
  },
  {
    id: "Navy Sailors Sunbathing",
    src: "/assets/Work/2021/Navy sailors sunbathing, 2021 Oil on canvas 180x220cm 70.9x86.6 inches.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 220 cm",
    sizeInch: "70.9 x 86.6 inches",
    date: "2021",
  },
  {
    id: "Skull Scene",
    src: "/assets/Work/2021/Skull Scene, 2021 Oil on canvas 160x180 cm 63x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "160 x 180 cm",
    sizeInch: "63 x 70.9 inches",
    date: "2021",
  },
  {
    id: "Surgery",
    src: "/assets/Work/2021/Surgery, 2021 Oil on canvas 260x200cm 102.4x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "260 x 200 cm",
    sizeInch: "102.4 x 78.7 inches",
    date: "2021",
  },
  {
    id: "The End of the beautiful Era",
    src: "/assets/Work/2021/The end of the beautiful era, 2021 Oil on canvas 140x110cm 55.1x43.3 inches.webp",
    method: "Oil on canvas",
    sizeCm: "140 x 110 cm",
    sizeInch: "55.1 x 43.3 inches",
    date: "2021",
  },
  {
    id: "Village Party",
    src: "/assets/Work/2021/Village party, 2021 Oil on camvas 200x240cm 78.7x94.5 inches.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 240 cm",
    sizeInch: "78.7 x 94.5 inches",
    date: "2021",
  },
  {
    id: "Woman, her Daughters and a Doll",
    src: "/assets/Work/2021/Woman, her daughters and a doll, 2021 Oil on canvas 210x160cm 82.7x63 inches.webp",
    method: "Oil on canvas",
    sizeCm: "210 x 160 cm",
    sizeInch: "82.7 x 63 inches",
    date: "2021",
  },
];

export const work2022 = [
  {
    title: "2022",
    link: "2022",
    id: "Armenian Soldiers",
    src: "/assets/Work/2022/Armenian soldiers, 2022 Oil on canvas 180x120cm 70.9x47.2 inches.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 120 cm",
    sizeInch: "70.9 x 47.2 inches",
    date: "2022",
  },
  {
    id: "Forest Camping",
    src: "/assets/Work/2022/Forest camping, 2022 Oil on canvas 200x210cm 78.7x82.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 210cm",
    sizeInch: "78.7 x 82.7 inches",
    date: "2022",
  },
  {
    id: "Girls from the 1940s",
    src: "/assets/Work/2022/Girls from the 1940s, 2022 Oil on canvas 220x180cm 86.6x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.9 inches",
    date: "2022",
  },
  {
    id: "Grandma on the Beach",
    src: "/assets/Work/2022/Grandma on the beach, 2022 Oil on canvas 150x240cm 59x94.5 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 240cm",
    sizeInch: "59 x 94.5 inches",
    date: "2022",
  },
  {
    id: "Grandma Svetlana and others on the Beach Picnic",
    src: "/assets/Work/2022/Grandma Svetlana and others on the beach picnic, 2022 Oil on canvas 200x180cm 78.7x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 180 cm",
    sizeInch: "78.7 x 70.9 inches",
    date: "2022",
  },
  {
    id: "Grandma Svetlana reading her Speech",
    src: "/assets/Work/2022/Grandma Svetlana reading her speech, 2022 Oil on canvas 220x180cm 86.6x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.9 inches",
    date: "2022",
  },
  {
    id: "Grandma Valentina and my Mother on the Beach",
    src: "/assets/Work/2022/Grandma Valentina and my mother on the beach, 2022 Oil on canvas 150x200cm 59x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 200 cm",
    sizeInch: "59 x 78.7 inches",
    date: "2022",
  },
  {
    id: "Grandparents at the Party",
    src: "/assets/Work/2022/Grandparents at the party, 2022 Oil on acrylic print transfer on canvas 30x40cm 11.8x15.7 inches.webp",
    method: "Oil on acrylic print transfer on canvas",
    sizeCm: " 30 x 40 cm",
    sizeInch: "11.8 x 15.7 inches",
    date: "2022",
  },
  {
    id: "New Volkswagen",
    src: "/assets/Work/2022/New Volkswagen, 2022 Oil on canvas 180x140cm 70.9x55.1 inches.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 140 cm",
    sizeInch: "70.9 x 55.1 inches",
    date: "2022",
  },
  {
    id: "Seeing their Grandma 2",
    src: "/assets/Work/2022/Seeing their grandma 2, 2022 Oil on canvas 90x90cm 35.4x35.4 inches.webp",
    method: "Oil on canvas",
    sizeCm: "90 x 90 cm",
    sizeInch: "35.4 x 35.4 inches",
    date: "2022",
  },
  {
    id: "Two Boys on the Beach",
    src: "/assets/Work/2022/Two boys on the beach, 2022 Oil on canvas 50x70cm 19.7x27.6 inches.webp",
    method: "Oil on canvas",
    sizeCm: "50 x 70 cm",
    sizeInch: "19.7 x 27.6 inches",
    date: "2022",
  },
  {
    id: "Two sisters",
    src: "/assets/Work/2022/Two sisters, 2022 Oil on canvas 30x40cm 11.8x15.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "30 x 40 cm",
    sizeInch: "11.8 x 15.7 inches",
    date: "2022",
  },
];

export const work2023 = [
  {
    title: "2023",
    link: "2023",
    id: "Mums Picnic",
    src: "/assets/Work/2023/2023_mums_picnic_55x70cm_oil_on_canvas-3000x2350.webp",
    method: "Oil on canvas",
    sizeCm: "300 x 235 cm",
    sizeInch: "118.1 x 92.5 inches",
    date: "2023",
  },
  {
    id: "Camping with a Dog",
    src: "/assets/Work/2023/Camping with a dog, 2023 Oil on canvas 40x50cm 15.7x19.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "40 x 50 cm",
    sizeInch: "15.7 x 19.7 inches",
    date: "2023",
  },
  {
    id: "New Year's Party from the 1970s",
    src: "/assets/Work/2023/New Years party from the 1970s, 2023 Oil on Van Dyke on canvas 150x160cm 59x63 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 160 cm",
    sizeInch: "59 x 63 inches",
    date: "2023",
  },
];

export const work2024 = [
  {
    title: "2024",
    link: "2024",
    id: "Accidental Shot 2",
    src: "/assets/Work/2024/Accidental shot 2, 2024 Oil on canvas 150x200cm 59x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 200 cm",
    sizeInch: "59 x 78.7 inches",
    date: "2024",
  },
  {
    id: "Beach Scene",
    src: "/assets/Work/2024/Beach scene, 2024  Oil on canvas 170x220cm 66.9x86.6 inches.webp",
    method: "Oil on canvas",
    sizeCm: "170 x 220 cm",
    sizeInch: "66.9 x 86.6 inches",
    date: "2024",
  },
  {
    id: "Boys in a Blanket Tent",
    src: "/assets/Work/2024/Boys in a blanket tent, 2024 Oil on canvas 115x150cm 45.3x59 inches.webp",
    method: "Oil on canvas",
    sizeCm: "115 x 150 cm",
    sizeInch: "45.3 x 59 inches",
    date: "2024",
  },
  {
    id: "Chess Players 2",
    src: "/assets/Work/2024/Chess players 2, 2024 Oil on canvas 120x150cm 47.2x59 inches.webp",
    method: "Oil on canvas",
    sizeCm: "120 x 150 cm",
    sizeInch: "47.2 x 59 inches",
    date: "2024",
  },
  {
    id: "Mum's Picnic from the 80s",
    src: "/assets/Work/2024/Mums picnic from the 80s, 2024 Oil on canvas 50x60cm 19.7x23.6 inches.webp",
    method: "Oil on canvas",
    sizeCm: "50 x 60 cm",
    sizeInch: "19.7 x 23.6 inches",
    date: "2024",
  },
  {
    id: "Neptune's Day",
    src: "/assets/Work/2024/Neptunes Day, 2024 Oil on canvas 170x220cm 66.9x86.6 inches.webp",
    method: "Oil on canvas",
    sizeCm: "170 x 220 cm",
    sizeInch: "66.9 x 86.6 inches",
    date: "2024",
  },
  {
    id: "NHS Baby Vaccination from the 50s",
    src: "/assets/Work/2024/NHS baby vaccination from the 50s, 2024 Oil on canvas  140x150cm 55.1x59 inches.webp",
    method: "Oil on canvas",
    sizeCm: "140 x 150 cm",
    sizeInch: "55.1 x 59 inches",
    date: "2024",
  },
  {
    id: "Posing Family from the 20s",
    src: "/assets/Work/2024/Posing family from the 20s, 2024 Oil on canvas  180x210cm 70.9x82.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 210 cm",
    sizeInch: "70.9 x 82.7 inches",
    date: "2024",
  },
  {
    id: "Rootop Picnic",
    src: "/assets/Work/2024/Rooftop picnic, 2024 Oil on canvas 200x200cm 78.7x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 200 cm",
    sizeInch: "78.7 x 78.7 inches",
    date: "2024",
  },
  {
    id: "Tea Picnic in Fields from the 60s",
    src: "/assets/Work/2024/Tea picnic in fields from the 60s, 2024 Oil on canvas 180x200cm 70.9x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "70.9 x 78.7 inches",
    date: "2024",
  },
  {
    id: "Two Geologists and a Dog 2",
    src: "/assets/Work/2024/Two geologists and a dog 2, 2024  Oil on canvas 120x170cm 47.2x66.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "120 x 170 cm",
    sizeInch: "47.2 x 66.9 inches",
    date: "2024",
  },
  {
    id: "Two Kids in the Harbour",
    src: "/assets/Work/2024/Two kids in the harbour, 2024 Oil on canvas 120x180cm 47.2x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "120 x 180 cm",
    sizeInch: "47.2 x 70.9 inches",
    date: "2024",
  },
  {
    id: "Ukrainian Dance",
    src: "/assets/Work/2024/Ukrainian dance, 2024 Oil on canvas 130x195cm 51.2x76.8 inches.webp",
    method: "Oil on canvas",
    sizeCm: "130 x 195 cm",
    sizeInch: "51.2 x 76.8 inches",
    date: "2024",
  },
  {
    id: "Uncle, Nephews, Nieces",
    src: "/assets/Work/2024/Uncle, nephews, nieces, 2024 Oil on canvas 120x180cm 47.2x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "120 x 180 cm",
    sizeInch: "47.2 x 70.9 inches",
    date: "2024",
  },
  {
    id: "Vacation by the Lake",
    src: "/assets/Work/2024/Vacation by the lake, 2024 Oil on canvas 120x160cm 47.2x63 inches.webp",
    method: "Oil on canvas",
    sizeCm: "120 x 160 cm",
    sizeInch: "47.2 x 63 inches",
    date: "2024",
  },
];

export const work2025 = [
  {
    title: "2025",
    link: "2025",
    id: "Intruded Picnic",
    src: "/assets/Work/2025/Intruded picnic, 2025 Oil on canvas  185x200cm 72.8x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "185 x 200 cm",
    sizeInch: "72.8 x 78.7 inches",
    date: "2025",
  },
  {
    id: "Picnic by the Lake",
    src: "/assets/Work/2025/Picnic by the lake, 2025 Oil on canvas 220x180cm 86.6x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.9 inches",
    date: "2025",
  },
  {
    id: "Picnic on the Meadow",
    src: "/assets/Work/2025/Picnic on the meadow, 2025 Oil on canvas 100x140cm 39.4x55.1 inches.webp",
    method: "Oil on canvas",
    sizeCm: "100 x 140 cm",
    sizeInch: "39.4 x 55.1 inches",
    date: "2025",
  },
  {
    id: "Reclining Grandma",
    src: "/assets/Work/2025/Reclining grandma, 2025 Oil on canvas 155x185cm 61x72.8 inches.webp",
    method: "Oil on canvas",
    sizeCm: "155 x 185 cm",
    sizeInch: "61 x 72.8 inches",
    date: "2025",
  },
  {
    id: "Spinnerei Celebration",
    src: "/assets/Work/2025/Spinnerei celebration, 2025 Oil on canvas 310x200cm  122x78.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "310 x 200 cm",
    sizeInch: "122 x 78.7 inches",
    date: "2025",
  },
  {
    id: "Spinnerei female Workers from the 30s",
    src: "/assets/Work/2025/Spinnerei female workers from the 30s, 2025 Oil on canvas 80x80cm 31.5x31.5 inches.webp",
    method: "Oil on canvas",
    sizeCm: "80 x 80 cm",
    sizeInch: "31.5 x 31.5 inches",
    date: "2025",
  },
  {
    id: "Spinnerei Summer Camp",
    src: "/assets/Work/2025/Spinnerei summer camp, 2025 Oil on canvas 170x210cm 66.9x82.7 inches.webp",
    method: "Oil on canvas",
    sizeCm: "170 x 210 cm",
    sizeInch: "66.9 x 82.7 inches",
    date: "2025",
  },
];

export const worksOnPaper = [
  {
    title: "Works on Paper",
    link: "works-on-paper",
    id: "50s french Wedding",
    src: "/assets/Work/Paper/50-s french wedding, 2021  A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2021",
  },
  {
    id: "After Manet",
    src: "/assets/Work/Paper/After Manet, 2020 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2020",
  },
  {
    id: "Armenian Women",
    src: "/assets/Work/Paper/Armenian women, 2022 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2022",
  },
  {
    id: "Baby Sceptic",
    src: "/assets/Work/Paper/Baby sceptic, 2019 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2019",
  },
  {
    id: "By the Fountain",
    src: "/assets/Work/Paper/By the fountain, 2022 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2022",
  },
  {
    id: "Family Portrait",
    src: "/assets/Work/Paper/Family portrait, 2021 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2021",
  },
  {
    id: "French Coastline",
    src: "/assets/Work/Paper/French coastline, 2020 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2020",
  },
  {
    id: "Horses",
    src: "/assets/Work/Paper/Horses, 2021 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2021",
  },
  {
    id: "Hunt",
    src: "/assets/Work/Paper/Hunt, 2021 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2021",
  },
  {
    id: "Jewish Family blue",
    src: "/assets/Work/Paper/Jewish family blue, 2021  A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2021",
  },
  {
    id: "Medical Students",
    src: "/assets/Work/Paper/Medical students, 2023 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2023",
  },
  {
    id: "Mums Picnic 2",
    src: "/assets/Work/Paper/Mums picnic 2, 2022 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2022",
  },
  {
    id: "New Volkswagen",
    src: "/assets/Work/Paper/New volkswagen, 2022 57x40cm 22.4x15.7 inches.webp",
    method: "",
    sizeCm: "57 x 40 cm",
    sizeInch: "22.4 x 15.7 inches",
    date: "2022",
  },
  {
    id: "Quarantine Series 1",
    src: "/assets/Work/Paper/Quarantine series 1, 2020 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2020",
  },
  {
    id: "Quarantine Series 2",
    src: "/assets/Work/Paper/Quarantine series 2, 2020 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2020",
  },
  {
    id: "Quarantine Series 3",
    src: "/assets/Work/Paper/Quarantine series 3, 2020 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2020",
  },
  {
    id: "Seeing their Grandma",
    src: "/assets/Work/Paper/Seing their grandma, 2020 40x65cm 15.7x25.6 inches.webp",
    method: "",
    sizeCm: "40 x 65 cm",
    sizeInch: "15.7 x 25.6 inches",
    date: "2020",
  },
  {
    id: "Surgeons",
    src: "/assets/Work/Paper/Surgeons, 2020 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2020",
  },
  {
    id: "Surgeons 2",
    src: "/assets/Work/Paper/Surgeons 2, 2022 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2022",
  },
  {
    id: "Two Boys",
    src: "/assets/Work/Paper/Two boys, 2021 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2021",
  },
  {
    id: "Two Kids and a Doll",
    src: "/assets/Work/Paper/Two kids and a doll, 2020 A3 30x42cm 11.8x16.5 inches.webp",
    method: "",
    sizeCm: "A3 - 30 x 42 cm",
    sizeInch: "11.8 x 16.5 inches",
    date: "2020",
  },
  {
    id: "Village Girls",
    src: "/assets/Work/Paper/Village girls, 2022 A2 42х59 cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2022",
  },
  {
    id: "Woman, her Daughters and a Doll",
    src: "/assets/Work/Paper/Woman, her daughters and a doll, 2019 A2 42x59cm 16.5x23.2 inches.webp",
    method: "",
    sizeCm: "A2 - 42 x 59 cm",
    sizeInch: "16.5 x 23.2 inches",
    date: "2019",
  },
  {
    id: "Woman, her Daughters and a Doll 2",
    src: "/assets/Work/Paper/Woman, her daughters and a doll 2, 2020 40x55cm 15.7x21.7 inches.webp",
    method: "",
    sizeCm: "40 x 55 cm",
    sizeInch: "15.7 x 21.7 inches",
    date: "2020",
  },
];

export const exhibition2025_Spinnerei = [
  {
    title: "From under the Bed",
    title_detailled: "Group Show, Archiv Massiv, Leipzig, GER, 2025.",
    descriptionCard: {
      exhibitionTitle: "Spinnerei series",
      exhibitionLocation:
        "From under the Bed, group exhibition of LIA residents, Archiv Massiv, 2025, Leipzig, Germany",
      description:
        "This body of work came from my residency LIA at the Baumwolle Spinnerei, an old GDR yarn factory, now Leipzig's main cultural hub. I got access to the factory's photo archives through Archive Massive museum.\nSpinnerei factory was massive, almost like a town, with its own kindergartens, concert halls, canteens, sports centres, and libraries. The archive pictures feature various aspects of life there, but with a noticable propaganda aroma of constantly happy workers, excited children building plane models, and gatherings with amateur performances. It's extremely similar to USSR archives - those who didn't t were removed or forced to pretend. But almost every propaganda picture, at least before Photoshop, has bits of messier, more random reality tucked in. Someone is drinking from a bottle at an o cial jubilee, someone hugs a little too inappropriately, someone enjoys their fancy out t, and a bored kid falls asleep during the endless speeches. In a line of workers' faces, someone has a half-smile, someone looks sadder. The deeper you look, the more reality hollows out. After transferring several Spinnerei photographs onto large canvases, I began using painting to explore them. I look for true-life details, sometimes exaggerating them - for example, Drinking Party features a tiny background fragment of a photograph, where people are drinking wildly, nothing like propaganda. That fragment is enlarged monumentally, giving importance to a small moment that slipped through.\n The past is constantly getting instrumentalised. This performance of happy community life could now be weaponised by GDR forces to glorify GDR's industrial development and balanced lives, or, contrary, anti-socialist or West German forces, framing GDR people as inferior, even though some things, like women's careers or workers' security, were probably superior there. But what this photograph still contain is actually the lives of real people, even if caught in the moment, ful lling some propaganda narratives.I want to let people from the past return the gaze, claim their agency, ook back from their time to ours.\n My experience as someone with family from the USSR has shown me very early how nstrumentalization of the past can become a bridgehead for wars, imprisonments, and violence of all kinds. My experience enforces my visual language with despair and rage when dealing with past magery, and passion against the instrumentalization of history, and, contrastingly, tenderness for forgotten people whose stories never became books. These contrasts make my painting experience more complex and multilayered. The complexity of ideological narrativization, political utilization, and existential void of gone time all come through my brushwork.",
    },
    link: "2025-Spinnerei",
    id: "From under the Bed - interior 1",
    src: "/assets/Exhibition/2025Spinnerei/1 Spinnerei series, part of _From under the Bed_ group show, Archiv Massiv, Leipzig, 2025.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2025",
  },
  {
    id: "Spinnerei Celebration from 70s",
    src: "/assets/Exhibition/2025Spinnerei/2 Spinnerei Celebration from 70s, 310x200cm_122x78.7_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "310 x 200 cm",
    sizeInch: "122 x 78.7 inches",
    date: "2025",
  },
  {
    id: "Spinnerei Celebration from 70s, detail",
    src: "/assets/Exhibition/2025Spinnerei/3 Spinnerei Celebration, 310x200 cm_122x78.7_, oil on canvas, detail.webp",
    method: "Oil on canvas",
    sizeCm: "310 x 200 cm",
    sizeInch: "122 x 78.7 inches",
    date: "2025",
  },
  {
    id: "From under the Bed - interior 2",
    src: "/assets/Exhibition/2025Spinnerei/3.5 Spinnerei series, part of _From under the Bed_ group exhibition, Archiv Massiv, Leipzig, 2025.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2025",
  },
  {
    id: "Spinnerei summer Camp",
    src: "/assets/Exhibition/2025Spinnerei/4 Spinnerei summer camp, 170x210cm_66.9x82.6_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "170 x 210 cm",
    sizeInch: "66.9 x 82.6 inches",
    date: "2025",
  },
  {
    id: "Spinnerei summer Camp, detail",
    src: "/assets/Exhibition/2025Spinnerei/5 Spinnerei Summer Camp, 170x210cm_66.9x82.6_, oil on canvas, 2025, detail .webp",
    method: "Oil on canvas",
    sizeCm: "170 x 210 cm",
    sizeInch: "66.9 x 82.6 inches",
    date: "2025",
  },

  {
    id: "Drinking party Spinnerei",
    src: "/assets/Exhibition/2025Spinnerei/6 Drinking party Spinnerei, 180x220cm_70.8x86.6_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 220 cm",
    sizeInch: "70.8 x 86.6 inches",
    date: "2025",
  },
  {
    id: "From under the Bed - interior 3",
    src: "/assets/Exhibition/2025Spinnerei/7 Drinking party Spinnerei, 180x220cm_70.8x86.6_, oil on canvas, 2025, in situ.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2025",
  },
  {
    id: "Drinking party Spinnerei, detail",
    src: "/assets/Exhibition/2025Spinnerei/8 Drinking party Spinnerei, 180x220cm_70.8x86.6_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 220 cm",
    sizeInch: "70.8 x 86.6 inches",
    date: "2025",
  },
  {
    id: "Spinnerei female workers from the 30s",
    src: "/assets/Exhibition/2025Spinnerei/9 Spinnerei female workers from the 30s, 80x80 cm_31.4x31.4_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "80 x 80 cm",
    sizeInch: "31.4 x 31.4 inches",
    date: "2025",
  },
  {
    id: "Drinking party Spinnerei sketches",
    src: "/assets/Exhibition/2025Spinnerei/10 Drinking party Spinnerei sketches, 40x28cm_15.7x11_ each, oil on paper, 2025.webp",
    method: "Oil on canvas",
    sizeCm: "40 x 28 cm",
    sizeInch: "15.7 x 11 inches",
    date: "2025",
  },
];

export const exhibition2025_IntrudedPicnics = [
  {
    title: "Intruded Picnics",
    title_detailled: "End of Residency Show, Turps Banana, London, UK, 2025",
    descriptionCard: {
      exhibitionTitle: "Intruded Picnics",
      exhibitionLocation: "End of Residency Show, Turps Banana, London, UK, 2025",
      description:
        "For some time, I have worked with old photographs, transferring them onto canvas and intruding upon them with my bodily presence as a painter. For this project, I sourced archival photographs of British picnics from different periods of the twentieth century. These scenes are inaccessible to me not only because they belong to the past, but also because they represent a culture in which I will always remain a foreigner. I lived in Britain for a total of seven years, yet never fully felt at home. My native culture and British culture are profoundly different, and although I am knowledgeable about British literature, theatre, art, politics, and history, I lack a familial connection to it. I did not grow up with a grandmother’s stories or with a sense of history passed down through generations. No matter how long I might live there, I will remain a foreigner. Recently, the figure of the foreigner has increasingly come to be perceived as an intruder. By working with photographs of British picnics, I insert myself into someone else’s past in an attempt to establish a connection that I lack as an immigrant. I intrude not only through gesture and brushwork, but also through representational presence, introducing a clumsy female figure into the scenes. I thought of the picnic as a situation to which one is usually invited, while the immigrant is often the one who is not invited and is instead positioned within a discourse of intrusion. There is a certain irony in placing myself uninvited into the country’s past, arriving at picnics from the 1920s or 1950s. At the same time, this can be understood as a speculative effort to relate to and understand the culture of the past in order to better grasp the country’s present. What if there were no borders, neither between countries nor between times? What if we were able to move freely between places and eras? Do I need a visa to travel into the past?",
    },
    link: "2025-IntrudedPicnics",
    id: "Intruded Picnics - interior 1",
    src: "/assets/Exhibition/2025TurpsBanana/1 Intruded picnics, End of the Residency Show, Turps, London, 2025.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2025",
  },
  {
    id: "Picnic by the lake",
    src: "/assets/Exhibition/2025TurpsBanana/2 Picnic by the lake, 220x180cm_86.6x70.8_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.8 inches",
    date: "2025",
  },
  {
    id: "Picnic by the lake - detail",
    src: "/assets/Exhibition/2025TurpsBanana/3 Picnic by the lake, 220x180cm_86.6x70.8_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.8 inches",
    date: "2025",
  },
  {
    id: "Picnic by the lake - detail 2",
    src: "/assets/Exhibition/2025TurpsBanana/4 Picnic by the lake, 220x180cm_86.6x70.8_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.8 inches",
    date: "2025",
  },
  {
    id: "Intruded picnic",
    src: "/assets/Exhibition/2025TurpsBanana/5 Intruded picnic, 180x200cm_70.8x78.7_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "70.8 x 78.7 inches",
    date: "2025",
  },
  {
    id: "Intruded picnic - detail",
    src: "/assets/Exhibition/2025TurpsBanana/6 Intruded picnic, 180x200cm_70.8x78.7_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "70.8 x 78.7 inches",
    date: "2025",
  },
  {
    id: "Intruded picnic - detail 2",
    src: "/assets/Exhibition/2025TurpsBanana/7 Intruded picnic, 180x200cm_70.8x78.7_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "70.8 x 78.7 inches",
    date: "2025",
  },
  {
    id: "Intruded picnics - interior 2",
    src: "/assets/Exhibition/2025TurpsBanana/8 Picnic on the meadow, 100x140cm_39.3x55.1_, oil on canvas, 2025, in situ.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2025",
  },
  {
    id: "Picnic on the meadow",
    src: "/assets/Exhibition/2025TurpsBanana/9 Picnic on the meadow, 100x140cm_39.3x55.1_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "100 x 140 cm",
    sizeInch: "38.3 x 55.1 inches",
    date: "2025",
  },
  {
    id: "Picnic on the meadow - detail",
    src: "/assets/Exhibition/2025TurpsBanana/10 Picnic on the meadow, 100x140cm_39.3x55.1_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "100 x 140 cm",
    sizeInch: "38.3 x 55.1 inches",
    date: "2025",
  },
  {
    id: "Picnic on the meadow - detail 2",
    src: "/assets/Exhibition/2025TurpsBanana/11 Picnic on the meadow 100x140cm_39.3x55.1_, oil on canvas, 2025, detail.webp",
    method: "Oil on canvas",
    sizeCm: "100 x 140 cm",
    sizeInch: "38.3 x 55.1 inches",
    date: "2025",
  },
  {
    id: "Intruded picnics - interior 3",
    src: "/assets/Exhibition/2025TurpsBanana/12 Picnic by the lake, 220x180cm_86.6x70.8_, oil on canvas, 2025, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "86.6 x 70.8 inches",
    date: "2025",
  },
];

export const exhibition2024_SongForBritain = [
  {
    title: "A Song of unrequited Love to Britain",
    title_detailled: "Rupturexibit, Kingston-upon-Thames, UK, 2024",
    descriptionCard: {
      exhibitionTitle: "A Song of unrequited Love to Britain",
      exhibitionLocation: "Rupturexibit, Kingston-upon-Thames, UK, 2024",
      description:
        "'A song of unrequited love to Britain', presents works from my residence at RuptureXIBIT space in London. It was very strange to ruturn to work in Kingston-upon-Thames, which was the place where my complex and changing rollercoaster of relationships with the UK and its culture had started. From deep dives into British literature, music, and art from early childhood to complete apathy, from admiration to alienation, these relationships can evoke a song to sing. Even after 7 years here, I keep being a complete foreigner — even an intruder, outsider, which was allowing me to see everything from the outside - but still be somehow inside. I sourced some family photographs of the British past, spanning the 1920s to the 1980s, and transferred their compositions to large canvases to explore my feelings and painterly responses to their content. Through the language of colour, gesture, and touch, I engaged with the shared past of many Brits, a family history of the culture which is so familiar to me, but still so alien, to revisit, and reconsider my actually quite deep connection to it. Through this body of work, I question myself — so, what was it? Was it love? Was it requited",
    },
    link: "2024-TurpsBanana",
    id: "A Song of unrequited Love to Britain - interior 1",
    src: "/assets/Exhibition/2024Rupturexibit/1 A song of unrequited love for Britain,  Rupturexibit, London, 2024, exhibition view.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Boys in a blanket tent",
    src: "/assets/Exhibition/2024Rupturexibit/2 Boys in a blanket tent, 115x150cm, oil on canvas, 2024, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "115 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Rooftop picnic",
    src: "/assets/Exhibition/2024Rupturexibit/3 Rooftop picnic, 200x200cm, oil on canvas, 2024, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 200 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Rooftop picnic - detail 1",
    src: "/assets/Exhibition/2024Rupturexibit/4 Rooftop picnic, 200x200cm, oil on canvas, 2024, detail.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 200 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Rooftop picnic - detail 2",
    src: "/assets/Exhibition/2024Rupturexibit/5 Rooftop picnic, 200x200cm, oil on canvas, 2024, detail-2.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 200 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "A Song of unrequited Love to Britain - interior 2",
    src: "/assets/Exhibition/2024Rupturexibit/6 A song of unrequited love for Britain,  Rupturexibit, London, 2024, exhibition view - 2.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "NHS baby vaccination from 50s",
    src: "/assets/Exhibition/2024Rupturexibit/7 NHS baby vaccination from 50-s 140x150cm, oil on canvas, 2024, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "140 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "NHS baby vaccination from 50s - detail 1",
    src: "/assets/Exhibition/2024Rupturexibit/8 NHS baby vaccination from 50-s 140x150cm, oil on canvas, 2024, detail - 2.webp",
    method: "Oil on canvas",
    sizeCm: "140 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "NHS baby vaccination from 50s - detail 2",
    src: "/assets/Exhibition/2024Rupturexibit/9 NHS baby vaccination from 50-s 140x150cm, oil on canvas, 2024, detail.webp",
    method: "Oil on canvas",
    sizeCm: "140 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "A song of unrequited love for Britain - interior 3",
    src: "/assets/Exhibition/2024Rupturexibit/10 A song of unrequited love for Britain,  Rupturexibit, London, 2024, exhibition view - 3.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Boys in a blanket tent",
    src: "/assets/Exhibition/2024Rupturexibit/11 Boys in a blanket tent, 115x150cm, oil on canvas, 2024, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "115 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Boys in a blanket tent - detail 1",
    src: "/assets/Exhibition/2024Rupturexibit/12 Boys in a blanket tent, 115x150cm, oil on canvas, 2024, detail 2.webp",
    method: "Oil on canvas",
    sizeCm: "115 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Boys in a blanket tent - detail 2",
    src: "/assets/Exhibition/2024Rupturexibit/14 Boys in a blanket tent, 115x150cm, oil on canvas, 2024, detail.webp",
    method: "Oil on canvas",
    sizeCm: "115 x 150 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "A song of unrequited love for Britain - interior 4",
    src: "/assets/Exhibition/2024Rupturexibit/15 A song of unrequited love for Britain,  Rupturexibit, London, 2024, exhibition view, acompanying  text.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Tea picnic in the fields from 60s",
    src: "/assets/Exhibition/2024Rupturexibit/16 Tea picnic in fields from 60s 180x200, oil on canvas, 2024, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Tea picnic in the fields from 60s - detail",
    src: "/assets/Exhibition/2024Rupturexibit/17 Tea picnic in fields from 60s 180x200, oil on canvas, 2024, detail.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "Tea picnic in the fields from 60s - detail 2",
    src: "/assets/Exhibition/2024Rupturexibit/18 Tea picnic in fields from 60s 180x200, oil on canvas, 2024, detail - 2.webp",
    method: "Oil on canvas",
    sizeCm: "180 x 200 cm",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "A song of unrequited love for Britain - interior 5",
    src: "/assets/Exhibition/2024Rupturexibit/19 A song of unrequited love for Britain,  Rupturexibit, London, 2024, exhibition view, accompanying  text.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2024",
  },
  {
    id: "A song of unrequited love for Britain - interior 6",
    src: "/assets/Exhibition/2024Rupturexibit/20 A song of unrequited love for Britain,  Rupturexibit, London, 2024, exhibition view - 4.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2024",
  },
];

export const exhibition2023_Shtager = [
  {
    title: "Voices from a Suitcase",
    title_detailled: "Solo Show, Shtager gallery, London, UK, 2023.",
    descriptionCard: {
      exhibitionTitle: "Voices from a Suitcase",
      exhibitionLocation: "Shtager Gallery, London, 2023",
      description:
        "Every immigrant carries an additional suitcase of their national culture, history, and collective memory to their new place. This baggage can haunt or support, empower or isolate. migrant myself, I am exploring the sense of detachment from thnational experience and construction of ambiguous identities through my painting practice. I use mundane photographs from the distant past of my country or family and immerse my presence in them through the brushwork to find peace with the problematic history that I brought with me. In this series, voices from my suitcase merge with the vibrant voices of my painterly marks, conversing and interacting with each other, creating a dialogue to elaborate on the immigrant experience”.",
    },
    link: "2023-ShtagerGallery",
    id: "Voices from a Suitcase - interior 1",
    src: "/assets/Exhibition/2023Shtager/1 Voices from a suitcase, Shtager gallery, in situ.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Voices from a Suitcase - interior 2",
    src: "/assets/Exhibition/2023Shtager/2 Voices from a suitcase, Shtager Gallery, London, 2023 - 2.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Voices from a Suitcase - interior 3",
    src: "/assets/Exhibition/2023Shtager/3 Voices from a suitcase, Shtager Gallery, London, 2023 - 3.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Grandma on the beach - interior",
    src: "/assets/Exhibition/2023Shtager/4 Grandma on the beach, 150 x 240 cm_59x94.4_, Oil on canvas, 2022,  in situ.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 240 cm",
    sizeInch: "59 x 94.4 inches",
    date: "2022",
  },
  {
    id: "Voices from a Suitcase - interior 4",
    src: "/assets/Exhibition/2023Shtager/5 Voices from a suitcase Shtager Gallery, 2023 London - 4.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Beach Party",
    src: "/assets/Exhibition/2023Shtager/6 Beach party, 200x210cm_78.7x82.6_, oil on canvas, 2023, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "200 x 210 cm",
    sizeInch: "78.7 x 82.6 inches",
    date: "2023",
  },

  {
    id: "Voices from a Suitcase - interior 5",
    src: "/assets/Exhibition/2023Shtager/7 Voices from a suitcase, Shtager Gallery, London, 2023 - 5.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Voices from a Suitcase - interior 6",
    src: "/assets/Exhibition/2023Shtager/8 Voices from a suitcase, Shtager Gallery, London, 2023 - 6.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "New year's party from the 70s",
    src: "/assets/Exhibition/2023Shtager/9 New year s party from the 70s, 140x150cm_55.1x59_, oil on Van Dyke printed canvas, 2023, in situ.webp",
    method: "Oil on Van Dyke printed on canvas",
    sizeCm: "140 x 150 cm",
    sizeInch: "55.1 x 59 inches",
    date: "2023",
  },
  {
    id: "Mum at the Beach",
    src: "/assets/Exhibition/2023Shtager/10 Mum at the beach, 130x180cm_51.1x70.8_, oil on canvas, 2022, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "130 x 180 cm",
    sizeInch: "51.1 x 70.8 inches",
    date: "2022",
  },

  {
    id: "Voices from a Suitcase - interior 7",
    src: "/assets/Exhibition/2023Shtager/11 Voices from a suitcase, Shtager Gallery, London, 2023 - 7.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Cloth",
    src: "/assets/Exhibition/2023Shtager/12 Cloth, 275x360cm_108.2x141.7_, Van Dyck emulsion print of a found photograph on canvas, 2023, in situ.webp",
    method: "Van Dyke emulsion print of a found photograph on canvas",
    sizeCm: "275 x 360 cm",
    sizeInch: "108.2 x 141.7 inches",
    date: "2023",
  },
  {
    id: "Beach party - interior",
    src: "/assets/Exhibition/2023Shtager/13 Beach party, 200x210cm_78.7x82.6_, oil on canvas, 2023, in situ.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2023",
  },
  {
    id: "Voices from a Suitcase - interior 8",
    src: "/assets/Exhibition/2023Shtager/14 Voices from a suitcase, Shtager Gallery, London, 2023 - 8.webp",
    method: "Oil on canvas",
    sizeCm: " cm",
    sizeInch: " inches",
    date: "2023",
  },

  {
    id: "Mum's picnic",
    src: "/assets/Exhibition/2023Shtager/15 Mum s picnic, 70x55cm_27.5x21.6_, oil on printed photograph on canvas, 2023, in situ.webp",
    method: "Oil on printed photograph on canvas",
    sizeCm: "70 x 55 cm",
    sizeInch: "27.5 x 21.6 inches",
    date: "2023",
  },
  {
    id: "Grandma on the beach",
    src: "/assets/Exhibition/2023Shtager/16 Grandma on the beach, 150 x 240 cm_59x94.4_, oil on canvas, 2022, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "150 x 240 cm",
    sizeInch: "59 x 94.4 inches",
    date: "2022",
  },
  {
    id: "Navy sailors sunbathing - interior",
    src: "/assets/Exhibition/2023Shtager/17 Navy sailors sunbathing, 240x200cm_94.4x78.7_, oil on canvas, 2021, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "240 x 200 cm",
    sizeInch: "94.4 x 78.7 inches",
    date: "2021",
  },
  {
    id: "Navy sailors sunbathing",
    src: "/assets/Exhibition/2023Shtager/18 Navy sailors sunbathing, 240x200cm_94.4x78.7_, oil on canvas, 2021, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "240 x 200 cm cm",
    sizeInch: "94.4 x 78.7 inches",
    date: "2021",
  },

  {
    id: "Pediatric surgery 1",
    src: "/assets/Exhibition/2023Shtager/19 Pediatric surgery 1, 165x180cm_64.9x70.8_, oil on canvas, 2019, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "165 x 180 cm",
    sizeInch: "64.9 x 70.8 inches",
    date: "2019",
  },
  {
    id: "Two boys on the beach",
    src: "/assets/Exhibition/2023Shtager/20 Two boys on the beach, 50x70cm_19.6x27.5_, oil on canvas, 2023, in situ.webp",
    method: "Oil on canvas",
    sizeCm: "50 x 70 cm",
    sizeInch: "19.6 x 27.5 inches",
    date: "2023",
  },
];

export const exhibition2022_BarbicanArt = [
  {
    title: "When my Babushka joined the Reich",
    title_detailled: "Barbican Art Group Trust, London, UK, 2022.",
    descriptionCard: {
      exhibitionTitle: "When my Babushka joined the Reich",
      exhibitionLocation:
        "Solo exhibition at Barbican Art Group Trust, London, UK. Result of a residency awarded upon winning the Art Works Open Art Prize (2021).",
      description:
        "'When my Babushka joined the Reich' is a project and a show I accomplished in the residency of Barbican Arts Group Trust upon winning Art Works Open prize 2021. In this project, I was looking for a way to talk about the tough political context through the personal lens and through the physicality of the medium of painting. All the works are based on my family archive photographs, featuring the episodes of the lives of my two grandmothers. The polarising political opinions we have with them, which for far more polarised in the time of the show, were causing mistrust, tensions, quarrelling and continuous alienation - but at the same time happy and funny childhood memories when we were very close, did not go anywhere. Via painting over my grandmothers’ photographed life, I try to examine their world and how they came to their perspectives, approaching an ambiguous feeling of a misunderstandings between generations. I combined the paintings - as a way to intrude in their youth - with the contemporary cites from our chats with them - both mundane and grandmotherly like 'dear, you must eat 3 kiwis a day, I read in the newspaper it is very important' and propagandistic like 'Ukraine is ruled by fascists, don't you know?'.\n'When my babushka joined the Reich series continues the artist's research on the propaganda machine's impacts on individuals' lives. Katyas paintings might evoke ambiguous feelings from sympathy and regret to rage and despair. Speaking on complicated issues and relevant topics might be hard, but surprisingly this is exactly what attracts us to art. The catharsis as a release of emotions and empowering practice is a unique experience that might be gained in it. In her practice, Katya consistently challenges and explores sophisticated questions of political and ideological repressions, power and fear, authorities, and violence. Media theorist Vilém Flusser in his 'Towards a Philosophy of Photography' essays studies the reception of photographs in mass media. Flusser emphasises the current domination of images and their mysterious power to program us to act in a ritual fashion. According to Flusser, the image becomes the model for its receivers' actions. Katya Granova uncovers the images' manipulative mechanisms through her personal stories. Her artistic method is based on personal and found archives, painting, text, cyanotype, and various image transfer techniques.' \nOxana Chvyakina, guest curator'",
    },
    link: "2022-BarbicanArtGroupTrust",
    id: "When my Babushka joined the Reich - interior 1",
    src: "/assets/Exhibition/2022BarbicanArt/1 When my grandma joined the Reich, interior 1  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 2",
    src: "/assets/Exhibition/2022BarbicanArt/2 When my grandma joined the Reich, interior 2  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 3",
    src: "/assets/Exhibition/2022BarbicanArt/3 When my grandma joined the Reich, interior 6  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 4",
    src: "/assets/Exhibition/2022BarbicanArt/4 When my grandma joined the Reich, interior 8  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 5",
    src: "/assets/Exhibition/2022BarbicanArt/5 When my grandma joined the Reich, interior 10  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 6",
    src: "/assets/Exhibition/2022BarbicanArt/9 When my grandma joined the Reich, interior 4  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 7",
    src: "/assets/Exhibition/2022BarbicanArt/9.5 When my grandma joined the Reich, interior 12  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my Babushka joined the Reich - interior 8",
    src: "/assets/Exhibition/2022BarbicanArt/10 Grandma Sverlana reading her speech-2, 25x35cm, 2022 and Grandparents on the party, 35x45cm, oil on acrylic transfer on canvas, 2022, in situ.webp",
    method: "left: Grandma Svetlana reading her speech 2 / 25 x 35 cm",
    sizeCm: "right:  Grandparents on the Party / 35 x 40 cm",
    sizeInch: "Oil on acrylic transfer on canvas",
    date: "2022",
  },
  {
    id: "Girls from the 40s",
    src: "/assets/Exhibition/2022BarbicanArt/11 Girls from the 40s, oil  on canvas, 220x180cm, 2022, in sutu.webp",
    method: "Oil on canvas",
    sizeCm: "220 x 180 cm",
    sizeInch: "",
    date: "2022",
  },
  {
    id: "When my grandma joined the Reich - interior 9",
    src: "/assets/Exhibition/2022BarbicanArt/12 When my grandma joined the Reich, interior 15  2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "",
  },
  {
    id: "When my grandma joined the Reich - interior 10",
    src: "/assets/Exhibition/2022BarbicanArt/13 When my grandma joined the Reich, interior 3 2022.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "",
  },
];

export const exhibition2021 = [
  {
    title: "Act 1. Scene 5",
    title_detailled: "Sphera Fund, Moscow, RU, 2021",
    descriptionCard: {
      exhibitionTitle: "",
      exhibitionLocation: "",
      description: "",
    },
    link: "2021",
    id: "Feast Scene",
    src: "/assets/Exhibition/2021/Feast Scene, 2021 Oil on canvas 230x180cm 90.6x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "230 x 180 cm",
    sizeInch: "90.6 x 70.9 inches",
    date: "2021",
  },
  {
    id: "Skull Scene",
    src: "/assets/Exhibition/2021/Skull Scene, 2021 Oil on canvas 160x180cm 63x70.9 inches.webp",
    method: "Oil on canvas",
    sizeCm: "160 x 180 cm",
    sizeInch: "63 x 70.9 inches",
    date: "2021",
  },
  {
    id: "interior",
    src: "/assets/Exhibition/2021/_MG_0014_edit-1800x1200.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2021",
  },
  {
    id: "interior",
    src: "/assets/Exhibition/2021/gertrude interior-1800x1200.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2021",
  },
  {
    id: "interior",
    src: "/assets/Exhibition/2021/Skull Scene interior 2-4500x3000.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2021",
  },
  {
    id: "interior",
    src: "/assets/Exhibition/2021/_MG_0044_edit-1800x1200.webp",
    method: "",
    sizeCm: "",
    sizeInch: "",
    date: "2021",
  },
];

// get first element of each album for title/link; order of albums in Work-component

export const thumbsWork = [
  work2025[0],
  work2024[0],
  work2023[0],
  work2022[0],
  work2021[0],
  work2020[0],
  work2019[0],
  worksOnPaper[0],
];

export const thumbsExhibition = [
  exhibition2025_Spinnerei[0],
  exhibition2025_IntrudedPicnics[0],
  exhibition2024_SongForBritain[0],
  exhibition2023_Shtager[0],
  exhibition2022_BarbicanArt[0],
  exhibition2021[0],
];
